### ISSUE TITLE
ModuleNotFoundError: No module named 'routes.toKindle'

### ISSUE THREAD

**Issue by berettavexee** [ebanDev/europresse-lib#1]
The **__init__.py** file makes a reference to the ".**toKindle**" library which is not present in the git repository. 
Removing the reference solves the problem. 

Le fichier **__init__.py** fait une référence à la bibliothéque "**.toKindle**" qui n'est pas présente dans le dépot git. 
Supprimer la référence règle le problème.

**Comment by ebanDev** [comment]
Hey ! Thx for reporting this issue, imma fix that in a few days ;)

**Comment by ebanDev** [comment]
Fixed in c45a89302ff17714a3e2900c50edc9dc9612da42, the mentioned function will be implemented in the future.
